### ISSUE TITLE
Failed to start monero-bash-monerod.service

### ISSUE THREAD

**Issue by flolu** [hinto-janaiyo/monero-bash#3]
I get this error when running `monero-bash start all`:

```
Starting monerod...
Failed to start monero-bash-monerod.service: Unit monero-bash-monerod.service not found.
monero-bash error: Could not start monerod
Exiting...
```

Running all services individually with `monero-bash full` works fine.

**Comment by flolu** [comment]
The output of `sudo systemd-analyze verify monero-bash-monerod.service` is:

```
Configuration file /etc/systemd/system/monero-bash-monerod.service is marked executable. Please remove executable permission bits. Proceeding anyway.
/usr/lib/systemd/system/docker.socket:5: ListenStream= references a path below legacy directory /var/run/, updating /var/run/docker.sock → /run/docker.sock; please update the unit file accordingly.
```

**Comment by hinto-janai** [comment]
Seems to be a permission issue, fixed in 655b9f3f41858b6884e607a6de1704a7bceb4822. For now you can manually fix by running:
```
sudo chmod 600 /etc/systemd/system/monero-bash-monerod.service
sudo chmod 600 /etc/systemd/system/monero-bash-p2pool.service
sudo chmod 600 /etc/systemd/system/monero-bash-xmrig.service
```

Could I ask what distro you're running?

**Comment by flolu** [comment]
I've tried to change the permission of all three files with the commands you've provided. Unfortunately, I still get this error.

And I'm running Fedora 36

**Comment by hinto-janai** [comment]
It seems SELinux (installed by default on Fedora) causes some problems with user installed systemd services and binaries. Setting it to `Permissive` or  disabling it completely is a quick work-around and lets monero-bash work normally but I can't recommend this, it's installed for a reason, right?

I'll find a proper fix later, thanks for bringing this to my attention. For now I'd recommend using `monero-bash full` inside a `screen` or `tmux` session.
